import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { existsSync, readFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

// Dev HTTPS: mobile Safari / wallet APIs require a secure context. The cert is
// generated by gen-cert.mjs. But in Cloudflare tunnel mode (CLOUDFLARE_TUNNEL=1)
// cloudflared terminates TLS itself with a real trusted cert — then local vite
// runs over plain http and no separate self-signed host is needed.
const TUNNEL = process.env.CLOUDFLARE_TUNNEL === "1";

// Mount the backend routes under the `/api` prefix and proxy them to localhost:8787.
// This way the frontend is served from a single origin; /api/* works from anywhere.
const BACKEND = {
  target: process.env.BACKEND_URL ?? "http://localhost:8787",
  changeOrigin: true,
};

function devHttps() {
  if (TUNNEL) return undefined;
  const k = '.dev-cert/key.pem'
  const c = '.dev-cert/cert.pem'
  try {
    if (!existsSync(k) || !existsSync(c)) {
      execFileSync('node', ['gen-cert.mjs'], { stdio: 'inherit' })
    }
    return {
      key: readFileSync(k),
      cert: readFileSync(c),
    }
  } catch (e) {
    // eslint-disable-next-line no-console
    console.warn('HTTPS dev cert unavailable, starting with http:', e instanceof Error ? e.message : String(e))
    return undefined
  }
}

export default defineConfig({
  plugins: [react()],
  define: {
    'process.env': JSON.stringify({}),
    global: 'globalThis',
  },
  resolve: {
    alias: {
      buffer: 'buffer/',
    },
  },
  optimizeDeps: {
    include: ['buffer', 'process'],
  },
  server: {
    host: '0.0.0.0',
    // Accept Cloudflare quick tunnel Host headers (DNS-rebinding protection would
    // otherwise block foreign hosts). Both *.trycloudflare.com, LAN IP, and localhost.
    allowedHosts: ['.trycloudflare.com', 'localhost', '127.0.0.1', '172.20.10.2'],
    https: devHttps(),
    proxy: {
      // The frontend makes all requests under /api on its own origin.
      '/api': {
        ...BACKEND,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
})